```{python}
#| include: false

import os
import sys
import importlib
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

pd.set_option("display.max_columns", 50)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

sys.path.append(os.path.abspath("../code"))

import analysis
importlib.reload(analysis)
df = analysis.load_data()
```

# Part 2: Generalized estimating equations (GEEs)

> Fit an appropriate GEE to examine the association between marital satisfaction and time, including all covariates (do not include statistical interactions terms). Fit two models using different correlation structures:
>
> 1.  GEE 1: First-order autoregressive structure (AR1)
> 2.  GEE 2: Unstructured correlation matrix

This section used `statsmodels` version 0.14.6 package in a Python environment (version 3.13.1). Two GEE models were fitted using the `GEE` function. The AR(1) model was fitted with the `Autoregressive` covariance structure, while the unstructured model was fitted with `Unstructured` covariance structure. Robust (sandwich) standard errors were used in both models, as is the default for this package.

In GEE 1 (AR1), the `time` argument was set to `obs_time`, whereas in GEE 2 (the model using the unstructured covariance structure) used a `visit` count variable to represent the observation order for each individual and `obs_time` in the model to still represent the time variable. This is a requirment of the package and can be explored in the source code of the function published on GitHub[^1].

[^1]: <https://github.com/statsmodels/statsmodels/blob/main/statsmodels/genmod/cov_struct.py#L231>

GEE 2 (Unstructured) was fitted excluding the last two observations of individual *2191*, the only individual with more than 15 observations. This was necessary to accomodate restrictions in the covariance structure. The model fitted well with 3 811 observations (as oppose 3 813).

\newpage

## Question 4

> Present a single table (Table 2) with coefficient estimates, standard errors, and 95\% confidence intervals (CI) for both GEE models. Use robust (sandwich) standard errors throughout

@tbl-gee presents the estimated associations between marital satisfaction, time and covariates from two GEE models with different working correlation structures. Overall, the model results are very similar. This suggests that the results are stable with some sensitivity to the correlation structure.

```{python}
#| include: false

table2 = analysis.question2_pretty(df)
```

```{python}
#| label: tbl-gee
#| tbl-cap: GEE model estimates with robust standard errors and 95\% confidence intervals.
#| echo: false

# table2 = analysis.question2_pretty(df)
table2.style.set_properties(
    subset=["Variable"],
    **{"text-align": "left", "font-weight": "bold"}
).hide(axis="index")
```

\newpage

## Question 5

> Determine the most appropriate correlation structure and justify your choice. State which GEE (GEE 1 or GEE 2) you will use as your final model.

The two models, resulting from different correlation structures, produce very similar coefficient estimates. This indicates that the results are not highly sensitive to the choice of correlation structure. Some variation is observed in the width of the confidence intervals, with the AR(1) model generally producing narrower intervals.

The unstructured model required restricting the data to fewer time points to accommodate groups (individuals) with more than 15 observations, whereas the AR(1) model was able to use all available observations.

The AR(1) model is preferred as it is simpler, allows for the full use of the data, and is consistent with the expectation that observations closer in time are more strongly correlated than those further apart.

\newpage

## Question 6

> Based on your final GEE model (from Q5), fully interpret the effects of the following predictors on marital satisfaction. For each, provide the estimated coefficient, 95\% CI, and an interpretation:
>
> - Time
> - Premarital cohabitation
> - Household workload

**Time:** In the AR(1) model, the estimated coefficient for time is -0.009 (95\% CI: -0.009 to -0.008). On average, marital satisfaction decreases by 0.009 for every month that the respondent is married. The confidence interval does not include zero, providing strong evidence that time is a significant predictor for marital satisfaction (or dissatisfaction).

**Premarital cohabitation:** In the AR(1) model, the estimated coefficient for premarital cohabitation is 0.260 (95\% CI: -0.060 to 0.580). On average, individuals who cohabited before marriage have slightly higher marital satisfaction compared to those who did not. However, the confidence interval includes zero, indicating no strong evidence of an association between premarital cohabitation and satisfaction.

**Household workload:** In the AR(1) model, the estimated coefficient for household workload is -0.470 (95\% CI: -0.752 to -0.189). On average, individuals with higher household workloads have lower marital satisfaction compared to those with lower workloads. The confidence interval does not include zero, providing strong evidence of a negative association between household workload and marital satisfaction.

This section used GEE models to evaluate population-level associations between marital satisfaction and predictors. The next section will use linear mixed effects models to evaluate both population-level and individual-level associations, accounting for individual variation in trajectories over time.
