```{python}
#| include: false

import os
import sys
import importlib
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

pd.set_option("display.max_columns", 50)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

sys.path.append(os.path.abspath("../code"))

import analysis
importlib.reload(analysis)
df = analysis.load_data()
```

# Part 4: Model validation

## Question 10

> Present two residual diagnostic plots for your final LME model (Figures 3 and 4). One plot should depict the residuals, while the other plot should be related to the random effects. Do these plots look reasonable? Briefly discuss in two to three sentences whether the model assumptions appear to be satisfied.

@fig-residuals illustrate the residuals plot for the final LME model (LME 1). The plot shows a random scatter of residuals around zero, approximately symmetrically distributed. This suggests that the assumption of homoscedasticity is satisfied. a small number of outliers and slight variation in spread are observed at higher fitted values, these are not substantial enough to suggest an incorrectly defined model.

```{python}
#| include: false

lme1, lme2 = analysis.fit_lme_models(df)
```

```{python}
#| label: fig-residuals
#| fig-cap: "Residuals Plot for Final LME Model."

analysis.plot_residuals(lme1)
```

@fig-qqplot shows the QQ plot of the random intercepts for the final LME model (LME 1). The points approximately follow the reference line, suggesting that the random intercepts are approximately normally distributed. Some deviation from normality is observed at the tails.

```{python}
#| label: fig-qqplot
#| fig-cap: "QQ Plot of Residuals for Final LME Model."

analysis.plot_random_effects(lme1)
```