::: {.content-visible when-format="html"}

A Biostats III assignment.

:::


# Plagiarism Declaration {-}

I acknowledge that plagiarism is a serious form of academic misconduct and dishonesty.

I have read and understood the document, ‘Avoiding Plagiarism: A guide for students’ from
the University of Cape Town. I acknowledge that I understand that the utilisation of open
AI tools (such as ChatGPT) without proper acknowledgement and citation is also a form
of academic misconduct and is not allowed. 

I acknowledge and accept the institutional
penalties that are applied if I should plagiarise in any submitted work. 

I have been warned
that for coursework assessment: first-time and minor misconduct breaches will result in a
mark deduction and warning; and any repeat or major misconduct breaches will result in a
failing grade and possible escalation to the Faculty Misconduct Committee (at the course
convenor’s discretion).


# AI Tools Declaration  {-}
I declare that in the preparation of this assignment, I used ChatGPT (OpenAI GPT-5) as a support
tool. The tool was used for assistance with:

1. Clarifying statistical concepts (e.g., model interpretation, model fit metrics),
2. Refining Python code snippets.
3. Formatting mathematical expressions and tables in Quartro.


All statistical analyses, interpretation of results, and final critical reflections were conducted by me.
The AI tool did not generate findings, nor did it substitute for my own analysis, understanding, or
judgment. I have reviewed and edited the outputs to ensure accuracy, appropriateness, and alignment
with the course requirements.



::: {=latex}
\clearpage
\pagenumbering{arabic}
:::

# Marital Satisfaction Analysis
{{< include WMXJOL001.qmd >}}


# Appendix A: Python code for analysis

The full reproducible analysis pipeline is provided below.

<!-- {{< include code.qmd >}} -->

```markdown
{{< include ../code/analysis.py >}}
```