<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jolene Wium">
<meta name="dcterms.date" content="2026-04-01">

<title>Biostatistics Assignment</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="WMXJOL001 - Biostats 3 - Assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="WMXJOL001 - Biostats 3 - Assignment_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="WMXJOL001 - Biostats 3 - Assignment_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="WMXJOL001 - Biostats 3 - Assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="WMXJOL001 - Biostats 3 - Assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="WMXJOL001 - Biostats 3 - Assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="WMXJOL001 - Biostats 3 - Assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="WMXJOL001 - Biostats 3 - Assignment_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="WMXJOL001 - Biostats 3 - Assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="WMXJOL001 - Biostats 3 - Assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="WMXJOL001 - Biostats 3 - Assignment_files/libs/bootstrap/bootstrap-67270d1595a62d14f123c043d4fb2f18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#part-1-descriptive-data-analysis" id="toc-part-1-descriptive-data-analysis" class="nav-link active" data-scroll-target="#part-1-descriptive-data-analysis">Part 1: Descriptive data analysis</a>
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  </ul></li>
  <li><a href="#part-2-generalized-estimating-equations-gees" id="toc-part-2-generalized-estimating-equations-gees" class="nav-link" data-scroll-target="#part-2-generalized-estimating-equations-gees">Part 2: Generalized estimating equations (GEEs)</a>
  <ul>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a></li>
  </ul></li>
  <li><a href="#part-3-linear-mixed-effects-lme-model" id="toc-part-3-linear-mixed-effects-lme-model" class="nav-link" data-scroll-target="#part-3-linear-mixed-effects-lme-model">Part 3: Linear mixed effects (LME) model</a>
  <ul>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8</a></li>
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9</a></li>
  </ul></li>
  <li><a href="#part-4-model-validation" id="toc-part-4-model-validation" class="nav-link" data-scroll-target="#part-4-model-validation">Part 4: Model validation</a>
  <ul>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostatistics Assignment</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jolene Wium </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="part-1-descriptive-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="part-1-descriptive-data-analysis">Part 1: Descriptive data analysis</h2>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<blockquote class="blockquote">
<p>Present and discuss a single table (Table 1) summarizing the baseline characteristics of the individuals (first observation per individual). Stratify the table by sex.</p>
</blockquote>
<p><a href="#tbl-table1" class="quarto-xref">Table&nbsp;1</a> presents the baseline characteristics of the individuals in the dataset, stratified by sex. Males are on average 2.2 years older than females when first getting amarried. Females in the study population earned on average more than males. The majority of both sexes cohobted before marriage (both &gt; 85%). Females reported higher household workloads than males, with males taking on only 6.2% of the household workload on average, compared to 62.1% for females.</p>
<div class="cell" data-execution_count="2">
<div id="tbl-table1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Baseline characteristics stratified by sex.
</figcaption>
<div aria-describedby="tbl-table1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<style type="text/css">
#T_83786_row0_col0, #T_83786_row1_col0, #T_83786_row2_col0, #T_83786_row3_col0, #T_83786_row4_col0, #T_83786_row5_col0, #T_83786_row6_col0, #T_83786_row7_col0 {
  text-align: left;
}
</style>

<table id="T_83786" class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_83786_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable</th>
<th id="T_83786_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">female</th>
<th id="T_83786_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">male</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_83786_row0_col0" class="data row0 col0">Age at marriage (mean (SD))</td>
<td id="T_83786_row0_col1" class="data row0 col1">27.31 (4.70)</td>
<td id="T_83786_row0_col2" class="data row0 col2">29.59 (4.85)</td>
</tr>
<tr class="even">
<td id="T_83786_row1_col0" class="data row1 col0">Income (mean (SD))</td>
<td id="T_83786_row1_col1" class="data row1 col1">32502.84 (18539.35)</td>
<td id="T_83786_row1_col2" class="data row1 col2">30976.49 (16881.02)</td>
</tr>
<tr class="odd">
<td id="T_83786_row2_col0" class="data row2 col0">Cohabitation</td>
<td id="T_83786_row2_col1" class="data row2 col1"></td>
<td id="T_83786_row2_col2" class="data row2 col2"></td>
</tr>
<tr class="even">
<td id="T_83786_row3_col0" class="data row3 col0">&gt; 0</td>
<td id="T_83786_row3_col1" class="data row3 col1">42 (14.7%)</td>
<td id="T_83786_row3_col2" class="data row3 col2">25 (12.0%)</td>
</tr>
<tr class="odd">
<td id="T_83786_row4_col0" class="data row4 col0">&gt; 1</td>
<td id="T_83786_row4_col1" class="data row4 col1">243 (85.3%)</td>
<td id="T_83786_row4_col2" class="data row4 col2">184 (88.0%)</td>
</tr>
<tr class="even">
<td id="T_83786_row5_col0" class="data row5 col0">Housework allocation</td>
<td id="T_83786_row5_col1" class="data row5 col1"></td>
<td id="T_83786_row5_col2" class="data row5 col2"></td>
</tr>
<tr class="odd">
<td id="T_83786_row6_col0" class="data row6 col0">&gt; 0</td>
<td id="T_83786_row6_col1" class="data row6 col1">108 (37.9%)</td>
<td id="T_83786_row6_col2" class="data row6 col2">196 (93.8%)</td>
</tr>
<tr class="even">
<td id="T_83786_row7_col0" class="data row7 col0">&gt; 1</td>
<td id="T_83786_row7_col1" class="data row7 col1">177 (62.1%)</td>
<td id="T_83786_row7_col2" class="data row7 col2">13 (6.2%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><em>Note:</em> Continuous variables are presented as <em>mean (SD)</em>; categorical variables as <em>n (%)</em>.</p>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<blockquote class="blockquote">
<p>Present and interpret a mean longitudinal profile of satisfaction measurements by household workload (Figure 1).</p>
</blockquote>
<p><a href="#fig-mean-profile" class="quarto-xref">Figure&nbsp;1</a> depicts the mean longitudinal profile of satisfaction measurements by household workload. The plot shows that individuals with higher household workloads tend to have lower marital satisfaction over time, while those with lower household workloads tend to have higher marital satisfaction. This suggests a potential negative association between household workload and marital satisfaction, which may warrant further investigation.</p>
<div id="cell-fig-mean-profile" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-mean-profile" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mean-profile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="WMXJOL001%20-%20Biostats%203%20-%20Assignment_files/figure-html/fig-mean-profile-output-1.png" width="662" height="422" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-profile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Mean longitudinal profile of satisfaction by household workload.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<blockquote class="blockquote">
<p>Present and interpret a spaghetti plot of satisfaction measurements by premarital cohabitation (Figure 2).</p>
</blockquote>
<p><a href="#fig-spaghetti" class="quarto-xref">Figure&nbsp;2</a> shows the marital satisfaction score over time for each individual over time. The left hand graph depics satisfaction of individuals that chose not to cohabitate with their partners before getting married. The right hand shows those that did co-habitate before getting married.</p>
<p>In general, both groups show a clear downward trajectory over time with significant indivudual variation. The overall patterns appear similar across cohabitation groups.</p>
<div id="cell-fig-spaghetti" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-spaghetti" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spaghetti-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="WMXJOL001%20-%20Biostats%203%20-%20Assignment_files/figure-html/fig-spaghetti-output-1.png" width="662" height="422" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spaghetti-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Spaghetti Plot of Satisfaction by Premarital Cohabitation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This section evaluated visual trends in marital satisfaction over time. The next section will evaluate general population level trends in the data using Generalized Estimating Equations (GEEs).</p>
</section>
</section>
<section id="part-2-generalized-estimating-equations-gees" class="level2">
<h2 class="anchored" data-anchor-id="part-2-generalized-estimating-equations-gees">Part 2: Generalized estimating equations (GEEs)</h2>
<blockquote class="blockquote">
<p>Fit an appropriate GEE to examine the association between marital satisfaction and time, including all covariates (do not include statistical interactions terms). Fit two models using different correlation structures:</p>
<ol type="1">
<li>GEE 1: First-order autoregressive structure (AR1)</li>
<li>GEE 2: Unstructured correlation matrix</li>
</ol>
</blockquote>
<p>This section used <code>statsmodels</code> version 0.14.6 package in a Python environment (version 3.13.1). Two GEE models were fitted using the <code>GEE</code> function. The AR(1) model was fitted with the <code>Autoregressive</code> covariance structure, while the unstructured model was fitted with <code>Unstructured</code> covariance structure. Robust (sandwich) standard errors were used in both models, as is the default for this package.</p>
<p>In GEE 1 (AR1), the <code>time</code> argument was set to <code>obs_time</code>, whereas in GEE 2 (the model using the unstructured covariance structure) used a <code>visit</code> count variable to represent the observation order for each individual and <code>obs_time</code> in the model to still represent the time variable. This is a requirment of the package and can be explored in the source code of the function published on GitHub<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>GEE 2 (Unstructured) was fitted excluding the last two observations of individual <em>2191</em>, the only individual with more than 15 observations. This was necessary to accomodate restrictions in the covariance structure. The model fitted well with 3 811 observations (as oppose 3 813).</p>
<section id="question-4" class="level3">
<h3 class="anchored" data-anchor-id="question-4">Question 4</h3>
<blockquote class="blockquote">
<p>Present a single table (Table 2) with coefficient estimates, standard errors, and 95% confidence intervals (CI) for both GEE models. Use robust (sandwich) standard errors throughout</p>
</blockquote>
<p><a href="#tbl-gee" class="quarto-xref">Table&nbsp;2</a> presents the estimated associations between marital satisfaction, time and covariates from two GEE models with different working correlation structures. Overall, the model results are very similar. This suggests that the results are stable with some sensitivity to the correlation structure.</p>
<div class="cell" data-execution_count="5">
<div id="tbl-gee" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gee-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: GEE model estimates with robust standard errors and 95% confidence intervals.
</figcaption>
<div aria-describedby="tbl-gee-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<style type="text/css">
#T_38d82_row0_col0, #T_38d82_row1_col0, #T_38d82_row2_col0, #T_38d82_row3_col0, #T_38d82_row4_col0, #T_38d82_row5_col0, #T_38d82_row6_col0 {
  text-align: left;
  font-weight: bold;
}
</style>

<table id="T_38d82" class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_38d82_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable</th>
<th colspan="2" id="T_38d82_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">AR(1)</th>
<th colspan="2" id="T_38d82_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Unstructured</th>
</tr>
<tr class="even">
<th id="T_38d82_level1_col0" class="col_heading level1 col0" data-quarto-table-cell-role="th"></th>
<th id="T_38d82_level1_col1" class="col_heading level1 col1" data-quarto-table-cell-role="th">Estimate (SE)</th>
<th id="T_38d82_level1_col2" class="col_heading level1 col2" data-quarto-table-cell-role="th">95% CI</th>
<th id="T_38d82_level1_col3" class="col_heading level1 col3" data-quarto-table-cell-role="th">Estimate (SE)</th>
<th id="T_38d82_level1_col4" class="col_heading level1 col4" data-quarto-table-cell-role="th">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_38d82_row0_col0" class="data row0 col0">Intercept</td>
<td id="T_38d82_row0_col1" class="data row0 col1">7.543 (0.366)</td>
<td id="T_38d82_row0_col2" class="data row0 col2">6.825 to 8.261</td>
<td id="T_38d82_row0_col3" class="data row0 col3">7.599 (0.886)</td>
<td id="T_38d82_row0_col4" class="data row0 col4">5.863 to 9.335</td>
</tr>
<tr class="even">
<td id="T_38d82_row1_col0" class="data row1 col0">Male (vs Female)</td>
<td id="T_38d82_row1_col1" class="data row1 col1">-0.403 (0.144)</td>
<td id="T_38d82_row1_col2" class="data row1 col2">-0.685 to -0.122</td>
<td id="T_38d82_row1_col3" class="data row1 col3">-0.748 (0.372)</td>
<td id="T_38d82_row1_col4" class="data row1 col4">-1.478 to -0.019</td>
</tr>
<tr class="odd">
<td id="T_38d82_row2_col0" class="data row2 col0">Time</td>
<td id="T_38d82_row2_col1" class="data row2 col1">-0.009 (0.000)</td>
<td id="T_38d82_row2_col2" class="data row2 col2">-0.009 to -0.008</td>
<td id="T_38d82_row2_col3" class="data row2 col3">-0.009 (0.000)</td>
<td id="T_38d82_row2_col4" class="data row2 col4">-0.009 to -0.008</td>
</tr>
<tr class="even">
<td id="T_38d82_row3_col0" class="data row3 col0">Age at marriage</td>
<td id="T_38d82_row3_col1" class="data row3 col1">0.014 (0.011)</td>
<td id="T_38d82_row3_col2" class="data row3 col2">-0.008 to 0.037</td>
<td id="T_38d82_row3_col3" class="data row3 col3">0.022 (0.024)</td>
<td id="T_38d82_row3_col4" class="data row3 col4">-0.026 to 0.070</td>
</tr>
<tr class="odd">
<td id="T_38d82_row4_col0" class="data row4 col0">Premarital cohabitation</td>
<td id="T_38d82_row4_col1" class="data row4 col1">0.260 (0.163)</td>
<td id="T_38d82_row4_col2" class="data row4 col2">-0.060 to 0.580</td>
<td id="T_38d82_row4_col3" class="data row4 col3">-0.087 (0.388)</td>
<td id="T_38d82_row4_col4" class="data row4 col4">-0.847 to 0.673</td>
</tr>
<tr class="even">
<td id="T_38d82_row5_col0" class="data row5 col0">Income</td>
<td id="T_38d82_row5_col1" class="data row5 col1">-0.000 (0.000)</td>
<td id="T_38d82_row5_col2" class="data row5 col2">-0.000 to 0.000</td>
<td id="T_38d82_row5_col3" class="data row5 col3">0.000 (0.000)</td>
<td id="T_38d82_row5_col4" class="data row5 col4">-0.000 to 0.000</td>
</tr>
<tr class="odd">
<td id="T_38d82_row6_col0" class="data row6 col0">Household workload</td>
<td id="T_38d82_row6_col1" class="data row6 col1">-0.470 (0.144)</td>
<td id="T_38d82_row6_col2" class="data row6 col2">-0.752 to -0.189</td>
<td id="T_38d82_row6_col3" class="data row6 col3">-0.471 (0.238)</td>
<td id="T_38d82_row6_col4" class="data row6 col4">-0.937 to -0.006</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="question-5" class="level3">
<h3 class="anchored" data-anchor-id="question-5">Question 5</h3>
<blockquote class="blockquote">
<p>Determine the most appropriate correlation structure and justify your choice. State which GEE (GEE 1 or GEE 2) you will use as your final model.</p>
</blockquote>
<p>The two models, resulting from different correlation structures, produce very similar coefficient estimates. This indicates that the results are not highly sensitive to the choice of correlation structure. Some variation is observed in the width of the confidence intervals, with the AR(1) model generally producing narrower intervals.</p>
<p>The unstructured model required restricting the data to fewer time points to accommodate groups (individuals) with more than 15 observations, whereas the AR(1) model was able to use all available observations.</p>
<p>The AR(1) model is preferred as it is simpler, allows for the full use of the data, and is consistent with the expectation that observations closer in time are more strongly correlated than those further apart.</p>
</section>
<section id="question-6" class="level3">
<h3 class="anchored" data-anchor-id="question-6">Question 6</h3>
<blockquote class="blockquote">
<p>Based on your final GEE model (from Q5), fully interpret the effects of the following predictors on marital satisfaction. For each, provide the estimated coefficient, 95% CI, and an interpretation:</p>
<ul>
<li>Time</li>
<li>Premarital cohabitation</li>
<li>Household workload</li>
</ul>
</blockquote>
<p><strong>Time:</strong> In the AR(1) model, the estimated coefficient for time is −0.009 (95% CI: −0.009 to −0.008). On average, marital satisfaction decreases by 0.009 for every month that the respondent is married. The confidence interval does not include zero, providing strong evidence that time is a significant predictor for marital satisfaction (or dissatisfaction).</p>
<p><strong>Premarital cohabitation:</strong> In the AR(1) model, the estimated coefficient for premarital cohabitation is 0.260 (95% CI: −0.060 to 0.580). On average, individuals who cohabited before marriage have slightly higher marital satisfaction compared to those who did not. However, the confidence interval includes zero, indicating no strong evidence of an association between premarital cohabitation and satisfaction.</p>
<p><strong>Household workload:</strong> In the AR(1) model, the estimated coefficient for household workload is −0.470 (95% CI: −0.752 to −0.189). On average, individuals with higher household workloads have lower marital satisfaction compared to those with lower workloads. The confidence interval does not include zero, providing strong evidence of a negative association between household workload and marital satisfaction.</p>
<p>This section used GEE models to evaluate population-level associations between marital satisfaction and predictors. The next section will use linear mixed effects models to evaluate both population-level and individual-level associations, accounting for individual variation in trajectories over time.</p>
</section>
</section>
<section id="part-3-linear-mixed-effects-lme-model" class="level2">
<h2 class="anchored" data-anchor-id="part-3-linear-mixed-effects-lme-model">Part 3: Linear mixed effects (LME) model</h2>
<blockquote class="blockquote">
<p>Fit an LME model to assess the association between marital satisfaction and time, including all covariates (do not include statistical interactions terms). Fit two models with different random-effects structures:</p>
<ol type="1">
<li>LME 1: Random intercepts only</li>
<li>LME 2: Random intercepts and random linear slopes for time</li>
</ol>
</blockquote>
<p>This section used <code>statsmodels</code> version 0.14.6 package in a Python environment (version 3.13.1). The LME models were fitted using the <code>MixedLM</code> function, using maximum likelihood estimation.</p>
<section id="question-7" class="level3">
<h3 class="anchored" data-anchor-id="question-7">Question 7</h3>
<blockquote class="blockquote">
<p>Present a single table (Table 3) with fixed-effect coefficient estimates, 95% confidence intervals, and relevant model comparison metrics for both LME models (LME 1 and LME 2). Present only the fixed effects - do not include the random-effects variance components in the table.</p>
</blockquote>
<p><a href="#tbl-table3" class="quarto-xref">Table&nbsp;3</a> provides a comparison of the fixed-effect coefficient estimates, 95% confidence intervals, and model comparison metrics for two LME models with different random-effects structures. LME 1 includes only random intercepts, while LME 2 includes both random intercepts and random slopes for time, allowing for individual variation in both baseline satisfaction and the rate of change in satisfaction over time. Model fit statistcs are provided at the bottom of the table for each model.</p>
<p>Overall, Log-likelihood, AIC and BIC indicate lower values for LME 2 than LME 1.</p>
<div class="cell" data-execution_count="6">
<div id="tbl-table3" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Comparing covariance matrixes for LME models.
</figcaption>
<div aria-describedby="tbl-table3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<style type="text/css">
#T_54c72_row0_col0, #T_54c72_row1_col0, #T_54c72_row2_col0, #T_54c72_row3_col0, #T_54c72_row4_col0, #T_54c72_row5_col0, #T_54c72_row6_col0 {
  text-align: left;
  font-weight: bold;
}
</style>

<table id="T_54c72" class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_54c72_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable</th>
<th colspan="2" id="T_54c72_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">LME 1: Random intercept</th>
<th colspan="2" id="T_54c72_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">LME 2: Random intercept + slope</th>
</tr>
<tr class="even">
<th id="T_54c72_level1_col0" class="col_heading level1 col0" data-quarto-table-cell-role="th"></th>
<th id="T_54c72_level1_col1" class="col_heading level1 col1" data-quarto-table-cell-role="th">Estimate (SE)</th>
<th id="T_54c72_level1_col2" class="col_heading level1 col2" data-quarto-table-cell-role="th">95% CI</th>
<th id="T_54c72_level1_col3" class="col_heading level1 col3" data-quarto-table-cell-role="th">Estimate (SE)</th>
<th id="T_54c72_level1_col4" class="col_heading level1 col4" data-quarto-table-cell-role="th">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_54c72_row0_col0" class="data row0 col0">Intercept</td>
<td id="T_54c72_row0_col1" class="data row0 col1">7.567 (0.376)</td>
<td id="T_54c72_row0_col2" class="data row0 col2">6.831 to 8.303</td>
<td id="T_54c72_row0_col3" class="data row0 col3">7.237 (0.416)</td>
<td id="T_54c72_row0_col4" class="data row0 col4">6.421 to 8.053</td>
</tr>
<tr class="even">
<td id="T_54c72_row1_col0" class="data row1 col0">Male (vs Female)</td>
<td id="T_54c72_row1_col1" class="data row1 col1">-0.431 (0.135)</td>
<td id="T_54c72_row1_col2" class="data row1 col2">-0.695 to -0.166</td>
<td id="T_54c72_row1_col3" class="data row1 col3">-0.491 (0.151)</td>
<td id="T_54c72_row1_col4" class="data row1 col4">-0.787 to -0.195</td>
</tr>
<tr class="odd">
<td id="T_54c72_row2_col0" class="data row2 col0">Time</td>
<td id="T_54c72_row2_col1" class="data row2 col1">-0.009 (0.000)</td>
<td id="T_54c72_row2_col2" class="data row2 col2">-0.009 to -0.008</td>
<td id="T_54c72_row2_col3" class="data row2 col3">-0.009 (0.002)</td>
<td id="T_54c72_row2_col4" class="data row2 col4">-0.013 to -0.004</td>
</tr>
<tr class="even">
<td id="T_54c72_row3_col0" class="data row3 col0">Age at marriage</td>
<td id="T_54c72_row3_col1" class="data row3 col1">0.012 (0.011)</td>
<td id="T_54c72_row3_col2" class="data row3 col2">-0.010 to 0.034</td>
<td id="T_54c72_row3_col3" class="data row3 col3">0.019 (0.013)</td>
<td id="T_54c72_row3_col4" class="data row3 col4">-0.006 to 0.044</td>
</tr>
<tr class="odd">
<td id="T_54c72_row4_col0" class="data row4 col0">Premarital cohabitation</td>
<td id="T_54c72_row4_col1" class="data row4 col1">0.218 (0.157)</td>
<td id="T_54c72_row4_col2" class="data row4 col2">-0.090 to 0.526</td>
<td id="T_54c72_row4_col3" class="data row4 col3">0.378 (0.176)</td>
<td id="T_54c72_row4_col4" class="data row4 col4">0.032 to 0.723</td>
</tr>
<tr class="even">
<td id="T_54c72_row5_col0" class="data row5 col0">Income</td>
<td id="T_54c72_row5_col1" class="data row5 col1">-0.000 (0.000)</td>
<td id="T_54c72_row5_col2" class="data row5 col2">-0.000 to 0.000</td>
<td id="T_54c72_row5_col3" class="data row5 col3">0.000 (0.000)</td>
<td id="T_54c72_row5_col4" class="data row5 col4">-0.000 to 0.000</td>
</tr>
<tr class="odd">
<td id="T_54c72_row6_col0" class="data row6 col0">Household workload</td>
<td id="T_54c72_row6_col1" class="data row6 col1">-0.496 (0.134)</td>
<td id="T_54c72_row6_col2" class="data row6 col2">-0.758 to -0.233</td>
<td id="T_54c72_row6_col3" class="data row6 col3">-0.539 (0.150)</td>
<td id="T_54c72_row6_col4" class="data row6 col4">-0.832 to -0.246</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="585cca3c" class="cell" data-results="asis" data-execution_count="7">
<div class="cell-output cell-output-display cell-output-markdown">
<p><em>Note:</em> Fixed effects are presented as estimate (SE) with 95% confidence intervals.<br>
<em>Model fit statistics:</em><br>
&gt; LME 1 AIC: 10654.57, BIC: 10710.79, Log-likelihood: -5318.28;<br>
&gt; LME 2 AIC: 12911.43, BIC: 12980.14, Log-likelihood: -6444.72.</p>
</div>
</div>
</section>
<section id="question-8" class="level3">
<h3 class="anchored" data-anchor-id="question-8">Question 8</h3>
<blockquote class="blockquote">
<p>Determine the most appropriate random-effects structure and justify your choice. State which LME (LME 1 or LME 2) is your final model.</p>
</blockquote>
<p>LME 1 is the preferred model. LME 2 is a nested version of LME 1, adding random slopes for time. Fixed effect estimates are similar in both models, indicating consistency across models. However, LME 1 has higher log-likelihood and lower AIC and BIC values than LME 2, indicating a better fit to the data. The random slope variance in LME 2 is non-zero, suggesting between-individual variation in time trends, however the model output warns of non-convergence. This model is too complex for the data.<br>
</p>
<p>This result is supported by the spagetti plot (<a href="#fig-spaghetti" class="quarto-xref">Figure&nbsp;2</a>) which showed clear downward individual trajectories over time.</p>
</section>
<section id="question-9" class="level3">
<h3 class="anchored" data-anchor-id="question-9">Question 9</h3>
<blockquote class="blockquote">
<p>Compare the estimated effects of the following predictors between your final GEE model (Q5) and your final LME model (Q8):</p>
<ul>
<li>Time</li>
<li>Premarital cohabitation</li>
<li>Household workload</li>
</ul>
</blockquote>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>WHEN KEEPING ALL OTHER COVARIATES THE SAME</p>
</div>
</div>
<p><strong>Time:</strong> In both GEE 1 (AR(1)) and LME 1 (random intercepts) model, the estimated coefficient for time is −0.009 (95% CI: −0.009 to −0.008). On average, marital satisfaction decreases by 0.009 for every month that the respondent is married. The confidence interval in both models do not include zero, providing strong evidence that time is a significant predictor for marital satisfaction (or dissatisfaction).</p>
<p><strong>Premarital cohabitation:</strong> In the AR(1) model, the estimated coefficient for premarital cohabitation is 0.260 (95% CI: −0.060 to 0.580), whereas in the LME 1 model it is 0.218 (95% CI: −0.090 to 0.526). On average, individuals who cohabited before marriage have slightly higher marital satisfaction compared to those who did not. However, the confidence interval includes zero in both models, indicating no strong evidence of an association between premarital cohabitation and satisfaction.</p>
<p><strong>Household workload:</strong> In the AR(1) model, the estimated coefficient for household workload is −0.470 (95% CI: −0.752 to −0.189), whereas in LME 1 it is −0.496 (95% CI: −0.758 to −0.233). On average, individuals with higher household workloads have lower marital satisfaction compared to those with lower workloads. The confidence interval does not include zero, providing strong evidence of a negative association between household workload and marital satisfaction.</p>
</section>
</section>
<section id="part-4-model-validation" class="level2">
<h2 class="anchored" data-anchor-id="part-4-model-validation">Part 4: Model validation</h2>
<section id="question-10" class="level3">
<h3 class="anchored" data-anchor-id="question-10">Question 10</h3>
<blockquote class="blockquote">
<p>Present two residual diagnostic plots for your final LME model (Figures 3 and 4). One plot should depict the residuals, while the other plot should be related to the random effects. Do these plots look reasonable? Briefly discuss in two to three sentences whether the model assumptions appear to be satisfied.</p>
</blockquote>
<p><a href="#fig-residuals" class="quarto-xref">Figure&nbsp;3</a> illustrate the residuals plot for the final LME model (LME 1). The plot shows a random scatter of residuals around zero, approximately symmetrically distributed. This suggests that the assumption of homoscedasticity is satisfied. a small number of outliers and slight variation in spread are observed at higher fitted values, these are not substantial enough to suggest an incorrectly defined model.</p>
<div id="cell-fig-residuals" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-residuals" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="WMXJOL001%20-%20Biostats%203%20-%20Assignment_files/figure-html/fig-residuals-output-1.png" width="566" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Residuals Plot for Final LME Model.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-qqplot" class="quarto-xref">Figure&nbsp;4</a> shows the QQ plot of the random intercepts for the final LME model (LME 1). The points approximately follow the reference line, suggesting that the random intercepts are approximately normally distributed. Some deviation from normality is observed at the tails.</p>
<div id="cell-fig-qqplot" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-qqplot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qqplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="WMXJOL001%20-%20Biostats%203%20-%20Assignment_files/figure-html/fig-qqplot-output-1.png" width="566" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qqplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: QQ Plot of Residuals for Final LME Model.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><a href="https://github.com/statsmodels/statsmodels/blob/main/statsmodels/genmod/cov_struct.py#L231" class="uri">https://github.com/statsmodels/statsmodels/blob/main/statsmodels/genmod/cov_struct.py#L231</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>